DROP TABLE IF EXISTS `settle_cdr_gprs_${yyyyMMdd}`;
CREATE TABLE `settle_cdr_gprs_${yyyyMMdd}`  (
`ID` bigint(20) NOT NULL,
`RECORD_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'RecordType is the identifier to differentiate the service type',
`NUMBER_A` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'The MSISDN number of Roaming Subscriber',
`NUMBER_B` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`NUMBER_DIALED` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Number Dialed is the international representation of the SMSC address used',
`MSISDN` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'The Mobile Subscriber ISDN number.',
`IMSI` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'The identifier which uniquely identifies the subscriber who has used the network.',
`EVENT_TIME_STAMP` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT ' The timestamp gives the start of the call event.\r\n              The time is given in the local time of the Sender PMN (or Serving Network).',
`LOCAL_EVENT_TIME_STAMP` datetime(0) NULL DEFAULT NULL COMMENT 'The timestamp gives the start of the call event.',
`EVENT_DURATION` int(11) NOT NULL COMMENT 'The item contains the actual total duration of a call event as a number of seconds.',
`DOWNLOAD_VOL` decimal(19, 2) NULL DEFAULT NULL COMMENT ' The item identifies the number of incoming Volumn',
`UPLOAD_VOL` decimal(19, 2) NULL DEFAULT NULL COMMENT 'The item identifies the number of outgoing Volumn',
`OPERATOR_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT ' unique identifier used to determine the network of roaming partner.',
`PRERATED_AMOUNT` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'The Network Identifier part of the Access Point Name (APN)',
`NULLI` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BROAD_WORKS` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TELE_SERVICE_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'A code which uniquely defines a TeleService.',
`BEARER_SERVICE_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OVERSEAS_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`VIDEO_INDICATOR` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SOURCE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`QUANTITY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CUST_NUMBER` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DESCRIPTION` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CALL_IDENTIFICATION` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TAIL_NUMBER` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ORIGINAL_FILE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`LINE_NUMBER` bigint(20) NULL DEFAULT NULL,
`INVOICING_PERIOD` char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SETTLE_ITEM` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CREATE_TIME` datetime(0) NULL DEFAULT NULL,
`RECEIVE_TIME` datetime(0) NOT NULL,
`FINISH_TIME` datetime(0) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
DROP TABLE IF EXISTS `settle_cdr_mms_${yyyyMMdd}`;
CREATE TABLE `settle_cdr_mms_${yyyyMMdd}`  (
`ID` bigint(20) NOT NULL,
`RECORD_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'RecordType is the identifier to differentiate the service type',
`NUMBER_A` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'The MSISDN number of Roaming Subscriber',
`NUMBER_B` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`NUMBER_DIALED` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Number Dialed is the international representation of the SMSC address used',
`MSISDN` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'The Mobile Subscriber ISDN number.',
`IMSI` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'The identifier which uniquely identifies the subscriber who has used the network.',
`EVENT_TIME_STAMP` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT ' The timestamp gives the start of the call event.\r\n              The time is given in the local time of the Sender PMN (or Serving Network).',
`LOCAL_EVENT_TIME_STAMP` datetime(0) NULL DEFAULT NULL COMMENT 'The timestamp gives the start of the call event.',
`EVENT_DURATION` int(11) NOT NULL COMMENT 'The item contains the actual total duration of a call event as a number of seconds.',
`DOWNLOAD_VOL` decimal(19, 2) NULL DEFAULT NULL COMMENT ' The item identifies the number of incoming Volumn',
`UPLOAD_VOL` decimal(19, 2) NULL DEFAULT NULL COMMENT 'The item identifies the number of outgoing Volumn',
`OPERATOR_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT ' unique identifier used to determine the network of roaming partner.',
`PRERATED_AMOUNT` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'The Network Identifier part of the Access Point Name (APN)',
`NULLI` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BROAD_WORKS` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TELE_SERVICE_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'A code which uniquely defines a TeleService.',
`BEARER_SERVICE_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OVERSEAS_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`VIDEO_INDICATOR` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SOURCE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`QUANTITY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CUST_NUMBER` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DESCRIPTION` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CALL_IDENTIFICATION` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TAIL_NUMBER` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ORIGINAL_FILE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`LINE_NUMBER` bigint(20) NULL DEFAULT NULL,
`INVOICING_PERIOD` char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SETTLE_ITEM` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CREATE_TIME` datetime(0) NULL DEFAULT NULL,
`RECEIVE_TIME` datetime(0) NOT NULL,
`FINISH_TIME` datetime(0) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
DROP TABLE IF EXISTS `settle_cdr_sms_${yyyyMMdd}`;
CREATE TABLE `settle_cdr_sms_${yyyyMMdd}`  (
`ID` bigint(20) NOT NULL,
`RECORD_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'RecordType is the identifier to differentiate the service type',
`NUMBER_A` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'The MSISDN number of Roaming Subscriber',
`NUMBER_B` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`NUMBER_DIALED` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Number Dialed is the international representation of the SMSC address used',
`MSISDN` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'The Mobile Subscriber ISDN number.',
`IMSI` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'The identifier which uniquely identifies the subscriber who has used the network.',
`EVENT_TIME_STAMP` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT ' The timestamp gives the start of the call event.\r\n              The time is given in the local time of the Sender PMN (or Serving Network).',
`LOCAL_EVENT_TIME_STAMP` datetime(0) NULL DEFAULT NULL COMMENT 'The timestamp gives the start of the call event.',
`EVENT_DURATION` int(11) NOT NULL COMMENT 'The item contains the actual total duration of a call event as a number of seconds.',
`DOWNLOAD_VOL` decimal(19, 2) NULL DEFAULT NULL COMMENT ' The item identifies the number of incoming Volumn',
`UPLOAD_VOL` decimal(19, 2) NULL DEFAULT NULL COMMENT 'The item identifies the number of outgoing Volumn',
`OPERATOR_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT ' unique identifier used to determine the network of roaming partner.',
`PRERATED_AMOUNT` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`APN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'The Network Identifier part of the Access Point Name (APN)',
`NULLI` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BROAD_WORKS` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TELE_SERVICE_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'A code which uniquely defines a TeleService.',
`BEARER_SERVICE_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OVERSEAS_CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`VIDEO_INDICATOR` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SOURCE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`SERVICE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`QUANTITY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CUST_NUMBER` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`DESCRIPTION` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CALL_IDENTIFICATION` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TAIL_NUMBER` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ORIGINAL_FILE` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`LINE_NUMBER` bigint(20) NULL DEFAULT NULL,
`INVOICING_PERIOD` char(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`SETTLE_ITEM` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`CREATE_TIME` datetime(0) NULL DEFAULT NULL,
`RECEIVE_TIME` datetime(0) NOT NULL,
`FINISH_TIME` datetime(0) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic

