#!/bin/bash

RUNNING_USER=billuser
APP_NAME=mvne-billing-credit-control
APP_VERSION=0.0.1-SNAPSHOT
PROFILE=creditcontrol

ADATE=`date +%Y-%m-%d`

APP_HOME=$(cd `dirname $0`;cd ..; pwd)
echo APP_HOME:$APP_HOME

LIB_PATH=$APP_HOME/lib/$PROFILE/
LOG_PATH=$APP_HOME/log/info/$APP_NAME.$ADATE.log
#APP_CONFIG=$APP_HOME/conf/application-$PROFILE.properties
APP_CONFIG=$APP_HOME/conf/

JVM_OPTS="-Xms2048M -Xmx4096M -Xloggc:$APP_HOME/log/error/$APP_NAME.gc.log -XX:+PrintGCDetails"

JAR_FILE=$APP_HOME/lib/$APP_NAME-$APP_VERSION.jar
pid=0
start(){
  checkpid
  if [ ! -n "$pid" ]; then
    echo JAR_FILE:$JAR_FILE
    nohup java $JVM_OPTS -Dspring.config.location=$APP_CONFIG -Dspring.profiles.active=$PROFILE -Dloader.path=$LIB_PATH -jar $JAR_FILE 1>/dev/null 2>&1 &
    echo "---------------------------------"
    echo "Program $APP_NAME started, press CTRL + C to exit console log!"
    echo "---------------------------------"
    sleep 5s
    tail -50f $LOG_PATH
  else
      echo "$APP_NAME is runing PID: $pid"
  fi

}

status(){
   checkpid
   if [ ! -n "$pid" ]; then
     echo "$APP_NAME not runing"
   else
     echo "$APP_NAME runing PID: $pid"
   fi
}


checkpid(){
    pid=`ps -ef |grep $JAR_FILE |grep -v grep |awk '{print $2}'`
}

stop(){
    checkpid
    if [ ! -n "$pid" ]; then
     echo "$APP_NAME not runing"
    else
      echo "$APP_NAME stop..."
      kill -9 $pid
    fi
}

restart(){
    stop
    sleep 1s
    start
}

case $1 in
          start) start;;
          stop)  stop;;
          restart)  restart;;
          status)  status;;
              *)  echo "require start|stop|restart|status"  ;;
esac
